services:
  server:
    container_name: dino-server
    image: python:3.9-slim
    working_dir: /app
    entrypoint: ""
    command: >
      bash -c "pip install websockets==12.0 &&
               python /app/game_server_ws.py"
    ports:
      - "50001:6666" # Port untuk WebSocket Server
    volumes:
      - ./work1:/app
    networks:
      - dinorace

  game_client:
    container_name: dino-client
    image: python:3.9-slim
    working_dir: /app
    command: python -m http.server 8000
    ports:
      - "8000:8000" # Port untuk Web Server Klien
    volumes:
      - ./work2:/app
    networks:
      - dinorace

networks:
  dinorace:
    driver: bridge